### ISSUE TITLE
batch_size to 2

### ISSUE THREAD

**Issue by Wansit99** [PeidongLi/SSR#12]
Excuse me, is it normal that I get an error when I change the value of batch_size to 2?

**Comment by Wansit99** [comment]
I have resolved the issue by modifying the code. However, I noticed that the GPU utilization is very low and occasionally drops to 0. What do you think could be the problem?

**Comment by PeidongLi** [comment]
The base code BEVFormer support bs=1 only. When you change bs=2 by modifying the code, the learning rate may also be adjusted for expected result.

**Comment by Wansit99** [comment]
> The base code BEVFormer support bs=1 only. When you change bs=2 by modifying the code, the learning rate may also be adjusted for expected result.

Thanks! But I have changed the bs=4 by using two 4090, May I also need to adjust the learning rate?

**Comment by Wansit99** [comment]
May I ask if I could add you on WeChat? I would like to discuss SSR-related questions with you further. I am a second-year graduate student that learning e2e at Wuhan University. Thank you for your time and consideration

**Comment by Wansit99** [comment]
> May I ask if I could add you on WeChat? I would like to discuss SSR-related questions with you further. I am a second-year graduate student that learning e2e at Wuhan University. Thank you for your time and consideration

如果您不方便公开微信 您也可以发送您的微信号到我的邮箱 wansit99@gmail.com 我添加您 十分感谢！

**Comment by Jozky86** [comment]
> > 我能加你微信吗？我想和你进一步讨论 SSR 相关的问题。我是武汉大学 e2e 专业的二年级研究生。谢谢你的时间和考虑
> 
> 如果您不方便公开微信您也可以将您的微信号发送到我的邮箱[wansit99@gmail.com](mailto:wansit99@gmail.com)我添加您或者您也可以我的微信号wansit99 十分感谢！
可以一起交流交流

**Comment by Wansit99** [comment]
> > > 我能加你微信吗？我想和你进一步讨论 SSR 相关的问题。我是武汉大学 e2e 专业的二年级研究生。谢谢你的时间和考虑
> > 
> > 
> > 如果您不方便公开微信您也可以将您的微信号发送到我的邮箱[wansit99@gmail.com](mailto:wansit99@gmail.com)我添加您或者您也可以我的微信号wansit99 十分感谢！
> > 可以一起交流交流

我的微信号 Wansit99 直接添加即可

**Comment by tsutsuji03** [comment]
@Wansit99 Thank you for sharing this information.If you don't mind, could you please release the code for multiple batch training?

**Comment by OrcunCanDeniz** [comment]
Most of the modern GPUs are heavily underutilized with batch_size=1. Thus, even though a bit pricey and not the cleanest way, but you can launch multiple training processes on the same gpu. eg. for 2 processes on single gpu. note the ` --cfg-options dist_params.backend=gloo `

```
python -m torch.distributed.run \
  --nproc_per_node=2 \
  --nnodes=1 \
  --master_port=2333 \
  tools/train.py \
    projects/configs/SSR/SSR_e2e.py \
    --launcher pytorch \
    --deterministic \
    --work-dir ./ \
    --cfg-options dist_params.backend=gloo
``` .

now you have virtual batchsize=2

**Comment by SUNWEN0** [comment]
> Excuse me, is it normal that I get an error when I change the value of batch_size to 2?

Hello, I also encountered an error when I changed batch_2 to 2. The error is as follows. May I ask if it is the same as yours and how did you solve it? Look forward to your reply


```
Traceback (most recent call last):
  File "tools/train.py", line 266, in <module>
    main()
  File "tools/train.py", line 255, in main
    custom_train_model(
  File "/data0/wenjiesun/SSR/SSR-main/projects/mmdet3d_plugin/SSR/apis/train.py", line 21, in custom_train_model
    custom_train_detector(
  File "/data0/wenjiesun/SSR/SSR-main/projects/mmdet3d_plugin/SSR/apis/mmdet_train.py", line 194, in custom_train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/wenjiesun/miniconda3/envs/vad/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)    #调用上面的train函数
  File "/home/wenjiesun/miniconda3/envs/vad/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs) #调用上面的run_iter
  File "/home/wenjiesun/miniconda3/envs/vad/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 29, in run_iter
    outputs = self.model.train_step(data_batch, self.optimizer,
  File "/home/wenjiesun/miniconda3/envs/vad/lib/python3.8/site-packages/mmcv/parallel/distributed.py", line 52, in train_step
    output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/wenjiesun/miniconda3/envs/vad/lib/python3.8/site-packages/mmdet/models/detectors/base.py", line 238, in train_step
    losses = self(**data)  # 调用本类自身的 forward 方法
  File "/home/wenjiesun/miniconda3/envs/vad/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data0/wenjiesun/SSR/SSR-main/projects/mmdet3d_plugin/SSR/SSR.py", line 214, in forward
    return self.forward_train(**kwargs)
  File "/home/wenjiesun/miniconda3/envs/vad/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 186, in new_func
    return old_func(*args, **kwargs)  
  File "/data0/wenjiesun/SSR/SSR-main/projects/mmdet3d_plugin/SSR/SSR.py", line 322, in forward_train
    losses_pts = self.forward_pts_train(img_feats, gt_bboxes_3d, gt_labels_3d,
  File "/data0/wenjiesun/SSR/SSR-main/projects/mmdet3d_plugin/SSR/SSR.py", line 173, in forward_pts_train
    outs = self.pts_bbox_head(pts_feats, img_metas, prev_bev,
  File "/home/wenjiesun/miniconda3/envs/vad/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/wenjiesun/miniconda3/envs/vad/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 186, in new_func
    return old_func(*args, **kwargs)  
  File "/data0/wenjiesun/SSR/SSR-main/projects/mmdet3d_plugin/SSR/SSR_head.py", line 461, in forward
    act_query = self.action_mln(latent_query, wp_vector)  #torch.Size([16, 1, 256])  论文公式（10）的Dt
  File "/home/wenjiesun/miniconda3/envs/vad/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data0/wenjiesun/SSR/SSR-main/projects/mmdet3d_plugin/SSR/SSR_head.py", line 79, in forward
    c = self.reduce(c)
  File "/home/wenjiesun/miniconda3/envs/vad/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/wenjiesun/miniconda3/envs/vad/lib/python3.8/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/wenjiesun/miniconda3/envs/vad/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/wenjiesun/miniconda3/envs/vad/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 96, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/wenjiesun/miniconda3/envs/vad/lib/python3.8/site-packages/torch/nn/functional.py", line 1847, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x24 and 12x256)
```
